export const REJECTED = "REJECTED";
export const RESOLVED = "RESOLVED";
export const SET_SELECTED_CURRENCY = "SET_SELECTED_CURRENCY";
export const START_POLLING_INDIVIDUAL = "START_POLLING_INDIVIDUAL";
export const START_POLLING_TOP_TEN = "START_POLLING_TOP_TEN";
export const START_REQUEST = "START_REQUEST";
export const STOP_POLLING = "STOP_POLLING";
